### ISSUE TITLE
Unable to create plugin

### ISSUE THREAD

**Issue by TestFirebaseLogin** [larshesel/vmq_elixir_plugin#3]

**Comment by TestFirebaseLogin** [comment]
Hi sir,i followed the Readme on the repo for creating elixir plugin,but im stuck at the step of installing the demo plugin.

vmq-admin plugin enable --name vmq_elixir_plugin --path `pwd`/_build/dev/

Here,i have replaced 'pwd' with the path to directory on mine system,but it keeps on saying,

Invalid value: "..." for flag: path,although i have checked and path is correct.
Any help will be greatly appreciated sir.

**Comment by larshesel** [comment]
Hi, could it be because the user VerneMQ is running as isn't allowed to read the files?

Otherwise there's a more complete guide over on the VerneMQ wiki: https://github.com/erlio/vernemq/wiki/VerneMQ-plugins-in-Elixir

**Comment by TestFirebaseLogin** [comment]
Sir,i have followed the above link as well already.
But iam stuck at different problem with it.
https://github.com/trarbr/vernemq_elixir_plugin/issues/2


And if i try to enable plugin from above repo, following readme in this repo..then i get again same error.

Also,any idea regarding permission of vernemq user,earlier both owner and group of folder were root ,i changed them both to vernemq,but still no luck.

Any suggestions sir?

**Comment by larshesel** [comment]
Answered on the other repo. Closing this one.
